package reaper

import (
	"strconv"
	"strings"
)

// BulkPlan is an ordered list of guarded single-track edits, proposed by an
// agent and applied — if the user accepts — as one REAPER undo step. It has
// no per-edit receipt or specific inverse: an applied plan reverses through
// REAPER's global undo (command 40029), which is correct because the whole
// plan already runs inside one undo block (PRD requirement 16).
type BulkPlan struct {
	Edits []TrackEdit
}

// Validate rejects an empty plan and checks every edit in it.
func (p BulkPlan) Validate() error {
	if len(p.Edits) == 0 {
		return ErrInvalidTrackEdit
	}
	for _, edit := range p.Edits {
		if err := edit.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// Ordered returns the plan's edits with every non-move kind first and every
// move last, each group keeping its original relative order. This settles
// PRD open question 6: renames, colors, and toggles never change a track's
// position, so applying them before any move means a move's index is never
// invalidated by an edit later in the same plan. Multiple moves within one
// plan still execute in the order given, exactly as a caller would expect
// from a sequence of single moves run back to back — each one's guard sees
// whatever the moves before it in this same plan already did.
func (p BulkPlan) Ordered() []TrackEdit {
	ordered := make([]TrackEdit, 0, len(p.Edits))
	for _, edit := range p.Edits {
		if edit.Kind != TrackEditMove {
			ordered = append(ordered, edit)
		}
	}
	for _, edit := range p.Edits {
		if edit.Kind == TrackEditMove {
			ordered = append(ordered, edit)
		}
	}
	return ordered
}

// Lua generates the whole plan as one script: every guard is checked first,
// without mutating anything, and only if every single one passes does any
// edit apply — all of them, inside one undo block. A guard failure anywhere
// applies nothing and reports which original track indices changed
// underneath the plan (PRD requirement 24).
func (p BulkPlan) Lua(receiptPath string) (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}
	if !strings.HasPrefix(receiptPath, "/") || strings.Contains(receiptPath, "\n") {
		return "", ErrInvalidTrackEdit
	}
	ordered := p.Ordered()

	var script strings.Builder
	script.WriteString("-- Generated by Ori: guarded bulk track-edit plan.\n")
	script.WriteString("local receipt_path = " + luaString(receiptPath) + "\n\n")
	script.WriteString(`local function write_receipt(body)
  local file = io.open(receipt_path, "wb")
  if file then
    file:write(body)
    file:close()
  end
end

-- Phase 1: verify every guard without applying anything. Track identity is
-- always checked by name at the index Ori read, exactly like a single edit.
local failed = {}
local folder_parents = {}
`)
	for i, edit := range ordered {
		script.WriteString("do -- guard " + strconv.Itoa(i+1) + "\n")
		script.WriteString("  local expected = " + luaString(edit.ExpectedName) + "\n")
		script.WriteString("  local tr = reaper.GetTrack(0, " + strconv.Itoa(edit.Index-1) + ")\n")
		script.WriteString("  local ok, current = false, nil\n")
		script.WriteString("  if tr then ok, current = reaper.GetSetMediaTrackInfo_String(tr, \"P_NAME\", \"\", false) end\n")
		script.WriteString("  if not tr or not ok or current ~= expected then\n")
		script.WriteString("    failed[#failed + 1] = " + strconv.Itoa(edit.Index) + "\n")
		script.WriteString("  end\n")
		if edit.Kind == TrackEditMove {
			script.WriteString("  if tr and ok and current == expected and reaper.GetMediaTrackInfo_Value(tr, \"I_FOLDERDEPTH\") > 0 then\n")
			script.WriteString("    folder_parents[#folder_parents + 1] = " + strconv.Itoa(edit.Index) + "\n")
			script.WriteString("  end\n")
		}
		script.WriteString("end\n")
	}
	script.WriteString(`
if #failed > 0 then
  write_receipt("guard_failed\n" .. table.concat(failed, ","))
  return
end
if #folder_parents > 0 then
  write_receipt("folder_parent\n" .. table.concat(folder_parents, ","))
  return
end

-- Phase 2: every guard passed. Apply everything inside one undo block.
reaper.Undo_BeginBlock()
`)
	for i, edit := range ordered {
		script.WriteString("do -- apply " + strconv.Itoa(i+1) + "\n")
		script.WriteString("  local tr = reaper.GetTrack(0, " + strconv.Itoa(edit.Index-1) + ")\n")
		script.WriteString(indentLua(edit.applyLua(), "  "))
		script.WriteString("end\n")
	}
	script.WriteString("reaper.Undo_EndBlock(" + luaString("Ori: apply "+strconv.Itoa(len(ordered))+" changes") + ", -1)\n")
	script.WriteString("reaper.TrackList_AdjustWindows(false)\n")
	script.WriteString("reaper.UpdateArrange()\n\n")
	script.WriteString("write_receipt(\"applied\\n" + strconv.Itoa(len(ordered)) + "\")\n")
	return script.String(), nil
}

// indentLua prefixes every line of a Lua snippet, so applyLua's output reads
// correctly nested inside the plan's per-edit `do...end` block.
func indentLua(lua, prefix string) string {
	lines := strings.Split(strings.TrimRight(lua, "\n"), "\n")
	for i, line := range lines {
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n") + "\n"
}

// BulkReceipt is what the generated plan script reported back. Applied is the
// authority on whether the plan changed anything at all — a plan is
// all-or-nothing, so there is no partial-apply state to represent.
// FailedIndices are the original 1-based track indices whose identity or
// folder-parent guard refused, for reporting which tracks prevented apply.
type BulkReceipt struct {
	Applied       bool
	AppliedCount  int
	FailedIndices []int
	Refusal       string
}

// ParseBulkReceipt reads the bulk receipt contract: "applied\n<count>",
// "guard_failed\n<indices>", or "folder_parent\n<indices>".
func ParseBulkReceipt(data []byte) (BulkReceipt, error) {
	text := string(data)
	outcome := text
	rest := ""
	if newline := strings.IndexByte(text, '\n'); newline >= 0 {
		outcome = text[:newline]
		rest = strings.TrimSpace(text[newline+1:])
	}
	switch strings.TrimSpace(outcome) {
	case "applied":
		count, err := strconv.Atoi(rest)
		if err != nil || count < 1 {
			return BulkReceipt{}, ErrInvalidReceipt
		}
		return BulkReceipt{Applied: true, AppliedCount: count}, nil
	case "guard_failed", "folder_parent":
		var indices []int
		if rest != "" {
			for _, field := range strings.Split(rest, ",") {
				index, err := strconv.Atoi(strings.TrimSpace(field))
				if err != nil {
					return BulkReceipt{}, ErrInvalidReceipt
				}
				indices = append(indices, index)
			}
		}
		return BulkReceipt{Applied: false, FailedIndices: indices, Refusal: strings.TrimSpace(outcome)}, nil
	default:
		return BulkReceipt{}, ErrInvalidReceipt
	}
}
